global:
    scrape_interval: 1s
     scrape_timeout: 1s 
    evaluation_interval: 1m
    external_labels:
        monitor: 'my-monitor'
  rule_files:  
      - '/etc/prometheus/alert.rules'
scrape_configs:
    - job_name: 'prometheus'
      target_groups:
          - targets: ['localhost:9090']
    - job_name: 'node-exporter'
      target_groups:
          - targets: ['node-exporter:9100']
    - job_name: 'cadvisor-exporter'
      scrape_interval: 1s
      target_groups:
          - targets: ['<IP>:9200']
